name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/workflows/**'
    
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/workflows/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag izm1chael/ctireporter:$(date +%s)
